# Generated by Django 2.0.2 on 2018-03-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='国家/地区')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='LeadRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='演员名称')),
            ],
            options={
                'db_table': 'leadroles',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='视频名称')),
                ('release_time', models.DateField(verbose_name='上映时间')),
                ('director', models.CharField(max_length=200, verbose_name='导演')),
                ('length', models.CharField(max_length=4, verbose_name='片长')),
                ('imdb_link', models.CharField(max_length=200, verbose_name='Imdb链接')),
                ('mark', models.CharField(max_length=4, verbose_name='评分')),
                ('cover_link', models.ImageField(upload_to='', verbose_name='封面图片')),
                ('summary', models.TextField(verbose_name='剧情简介')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_carousel', models.BooleanField(default=False, verbose_name='是否首页轮播展示')),
                ('is_sidebar', models.BooleanField(default=False, verbose_name='侧边栏推荐展示')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mydesign.Country', verbose_name='国家/地区')),
                ('lead_role', models.ManyToManyField(to='mydesign.LeadRole', verbose_name='主演')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='StyleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(max_length=20, verbose_name='风格类型')),
            ],
            options={
                'db_table': 'styletypes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱')),
                ('head_pic', models.ImageField(upload_to='', verbose_name='头像')),
                ('is_subscribe', models.BooleanField(default=True, verbose_name='是否订阅电子杂志')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='style_type',
            field=models.ManyToManyField(to='mydesign.StyleType', verbose_name='风格类型'),
        ),
    ]
