# Generated by Django 2.0.2 on 2018-03-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0002_auto_20180305_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(to='mydesign.User', verbose_name='喜欢'),
        ),
    ]
