# Generated by Django 2.0.2 on 2018-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0003_movie_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='head_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=250),
        ),
    ]
