# Generated by Django 2.0.2 on 2018-03-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0006_visited'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visited',
            table='visited',
        ),
    ]
