# Generated by Django 2.0.2 on 2018-03-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
