# Generated by Django 2.0.2 on 2018-03-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0009_auto_20180306_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
