# Generated by Django 2.0.2 on 2018-03-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0010_comment_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('pic', models.ImageField(upload_to='')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
