# Generated by Django 2.0.2 on 2018-03-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0011_advertise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertise',
            table='advertises',
        ),
    ]
