# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0012_auto_20180307_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(max_length=200, null=True, verbose_name='Imdb链接'),
        ),
    ]
